# Generated by Django 4.0 on 2022-05-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0002_alter_client_options_alter_distribution_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_operator',
            field=models.CharField(max_length=50, verbose_name='phone_operator'),
        ),
    ]
